[build]
  publish = "."
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "ADMIN_USER,ADMIN_PASS"

# Edge function protege /admin/* a nivel de servidor
[[edge_functions]]
  path = "/admin/*"
  function = "admin-auth"

[[edge_functions]]
  path = "/admin"
  function = "admin-auth"
