backend:
  name: git-gateway
  branch: main # Branch to update (change to master if applicable)

local_backend: true # Enable local file system access

media_folder: "assets/uploads" # Media files will be stored in the repo under assets/uploads
public_folder: "assets/uploads" # The src attribute for uploaded media will begin with /assets/uploads

collections:
  - name: "experiences" # Used in routes, e.g., /admin/collections/blog
    label: "Experiencias" # Used in the UI
    files:
      - name: "experiences"
        label: "Lista de Experiencias"
        file: "data/experiences.json"
        fields:
          - label: "Experiencias"
            name: "experiences"
            widget: "list"
            fields:
              - {label: "ID (unico)", name: "id", widget: "string"}
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Imagen", name: "image", widget: "image"}
              - {label: "Descripción", name: "description", widget: "text"}

  - name: "planes"
    label: "Planes"
    files:
      - name: "planes"
        label: "Lista de Planes"
        file: "data/planes.json"
        fields:
          - label: "Planes"
            name: "planes"
            widget: "list"
            fields:
              - {label: "ID (unico)", name: "id", widget: "string"}
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Medalla", name: "badge", widget: "string"}
              - {label: "Precio", name: "price", widget: "string"}
              - {label: "Duración", name: "duration", widget: "string"}
              - {label: "Subtítulo", name: "subtitle", widget: "string"}
              - {label: "Descripción", name: "description", widget: "text"}
              - label: "Incluye"
                name: "includes"
                widget: "list"
                summary: "{{fields.item}}"
                field: {label: "Item", name: "item", widget: "string"}
              - {label: "Imagen", name: "image", widget: "image"}
